/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import javax.swing.JOptionPane;
import org.neuroph.core.NeuralNetwork;

/**
 *
 * @author Usuario
 */
public class FrmDesercionEscolar extends javax.swing.JFrame {

    FrmCreditos frmCreditos = new FrmCreditos();
    FrmAutonomo frmAutonomo = new FrmAutonomo();

    /**
     * Creates new form FrmTransporte
     */
    public FrmDesercionEscolar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        buttonGroup7 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        rbtAA1 = new javax.swing.JRadioButton();
        rbtAA2 = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        txtResultado = new javax.swing.JTextField();
        btnCalcular = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        btnCreditos = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        rbtAA3 = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        rbtNoFO = new javax.swing.JRadioButton();
        rbtYesFO = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        rbtNAA1 = new javax.swing.JRadioButton();
        rbtNAA2 = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        rbtDeficientEconS = new javax.swing.JRadioButton();
        rbtRegularEconS = new javax.swing.JRadioButton();
        rbtGoodEconS = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        rbtNAC1 = new javax.swing.JRadioButton();
        rbtNAC2 = new javax.swing.JRadioButton();
        rbtNAC3 = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        rbtDeficientF = new javax.swing.JRadioButton();
        rbtRegularF = new javax.swing.JRadioButton();
        rbtGoodF = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        rbtDeficientES = new javax.swing.JRadioButton();
        rbtRegularES = new javax.swing.JRadioButton();
        rbtGoodES = new javax.swing.JRadioButton();
        btnAuto = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("NNTransporte");

        jPanel1.setBackground(new java.awt.Color(51, 255, 204));

        jLabel1.setFont(new java.awt.Font("Tahoma", 2, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Red Neuronal \"Desercion Escolar\"");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Academic Average:");

        buttonGroup1.add(rbtAA1);
        rbtAA1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        rbtAA1.setSelected(true);
        rbtAA1.setText("AA>=9.0");

        buttonGroup1.add(rbtAA2);
        rbtAA2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        rbtAA2.setText("7.5<=AA<9.0");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Resultado:");

        txtResultado.setBackground(new java.awt.Color(255, 255, 255));
        txtResultado.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        btnCalcular.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnCalcular.setText("Calcular");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });

        btnLimpiar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        btnSalir.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        btnCreditos.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnCreditos.setText("Créditos");
        btnCreditos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreditosActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Nombre:");

        txtNombre.setBackground(new java.awt.Color(255, 255, 255));

        buttonGroup1.add(rbtAA3);
        rbtAA3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        rbtAA3.setText("AA<7.5");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("First Option:");

        buttonGroup2.add(rbtNoFO);
        rbtNoFO.setSelected(true);
        rbtNoFO.setText("No");

        buttonGroup2.add(rbtYesFO);
        rbtYesFO.setText("Yes");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("No Accredited Assigments:");

        buttonGroup3.add(rbtNAA1);
        rbtNAA1.setSelected(true);
        rbtNAA1.setText("NAA = 0");

        buttonGroup3.add(rbtNAA2);
        rbtNAA2.setText("NAA > 0");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Economic Status:");

        buttonGroup4.add(rbtDeficientEconS);
        rbtDeficientEconS.setSelected(true);
        rbtDeficientEconS.setText("Deficient");

        buttonGroup4.add(rbtRegularEconS);
        rbtRegularEconS.setText("Regular");

        buttonGroup4.add(rbtGoodEconS);
        rbtGoodEconS.setText("Good");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("No Attending Class:");

        buttonGroup5.add(rbtNAC1);
        rbtNAC1.setSelected(true);
        rbtNAC1.setText("NAC > 15%");

        buttonGroup5.add(rbtNAC2);
        rbtNAC2.setText("0% < NAC <= 15%");
        rbtNAC2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtNAC2ActionPerformed(evt);
            }
        });

        buttonGroup5.add(rbtNAC3);
        rbtNAC3.setText(" NAC = 0%");
        rbtNAC3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtNAC3ActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Fitness:");

        buttonGroup6.add(rbtDeficientF);
        rbtDeficientF.setSelected(true);
        rbtDeficientF.setText("Deficient");

        buttonGroup6.add(rbtRegularF);
        rbtRegularF.setText("Regular");

        buttonGroup6.add(rbtGoodF);
        rbtGoodF.setText("Good");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Emotional Status:");

        buttonGroup7.add(rbtDeficientES);
        rbtDeficientES.setSelected(true);
        rbtDeficientES.setText("Deficient");

        buttonGroup7.add(rbtRegularES);
        rbtRegularES.setText("Regular");

        buttonGroup7.add(rbtGoodES);
        rbtGoodES.setText("Good");

        btnAuto.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnAuto.setText("Auto");
        btnAuto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAutoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel9)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addGap(41, 41, 41)
                                    .addComponent(txtResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(94, 94, 94)
                                    .addComponent(btnAuto)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 546, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(82, 82, 82))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel3)
                                                .addComponent(jLabel2))
                                            .addGap(93, 93, 93)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addComponent(rbtNoFO)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(rbtYesFO))
                                                .addComponent(rbtAA1))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(rbtAA2))
                                        .addComponent(jLabel8)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel4)
                                                .addComponent(jLabel7))
                                            .addGap(32, 32, 32)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addComponent(rbtNAA1)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(rbtNAA2))
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addComponent(rbtDeficientEconS)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(rbtRegularEconS)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(rbtGoodEconS))
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addComponent(rbtNAC1)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(rbtNAC2)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(rbtNAC3))
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addComponent(rbtDeficientF)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(rbtRegularF)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(rbtGoodF))
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(btnCalcular)
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                            .addComponent(rbtDeficientES)
                                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                            .addComponent(rbtRegularES)))
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(rbtGoodES)))))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(rbtAA3))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnLimpiar)
                        .addGap(34, 34, 34)
                        .addComponent(btnCreditos)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(rbtAA1)
                    .addComponent(rbtAA2)
                    .addComponent(rbtAA3))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(rbtNoFO)
                    .addComponent(rbtYesFO))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(rbtNAA1)
                    .addComponent(rbtNAA2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(rbtDeficientEconS)
                    .addComponent(rbtRegularEconS)
                    .addComponent(rbtGoodEconS))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(rbtNAC1)
                    .addComponent(rbtNAC2)
                    .addComponent(rbtNAC3))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(rbtDeficientF)
                    .addComponent(rbtRegularF)
                    .addComponent(rbtGoodF))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(rbtDeficientES)
                    .addComponent(rbtRegularES)
                    .addComponent(rbtGoodES))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCalcular)
                    .addComponent(btnLimpiar)
                    .addComponent(btnCreditos))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalir)
                    .addComponent(jLabel5)
                    .addComponent(txtResultado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAuto))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        if (txtNombre.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this,"Empty Field");

        } else {
            // load the saved network 
            NeuralNetwork neuralNetwork = NeuralNetwork.createFromFile("desercion_escolar_multilayer.nnet");

            // set network input
            int AA = -1;
            int FO = 0;
            int NAA = 0;
            int ECS = -1;
            int NAC = -1;
            int F = -1;
            int EMS = -1;

            if (rbtAA1.isSelected()) {
                AA = -1;
            } else if (rbtAA2.isSelected()) {
                AA = 0;
            } else {
                AA = 1;
            }

            if (rbtNoFO.isSelected()) {
                FO = 0;
            } else {
                FO = 1;
            }

            if (rbtNAA1.isSelected()) {
                NAA = 0;
            } else {
                NAA = 1;
            }

            if (rbtDeficientEconS.isSelected()) {
                ECS = -1;
            } else if (rbtRegularEconS.isSelected()) {
                ECS = 0;
            } else if (rbtGoodEconS.isSelected()) {
                ECS = 1;
            }

            if (rbtNAC1.isSelected()) {
                NAC = -1;
            } else if (rbtNAC2.isSelected()) {
                NAC = 0;
            } else if (rbtNAC3.isSelected()) {
                NAC = 1;
            }

            if (rbtDeficientF.isSelected()) {
                F = -1;
            } else if (rbtRegularF.isSelected()) {
                F = 0;
            } else if (rbtGoodF.isSelected()) {
                F = 1;
            }

            if (rbtDeficientES.isSelected()) {
                EMS = -1;
            } else if (rbtRegularES.isSelected()) {
                EMS = 0;
            } else if (rbtGoodES.isSelected()) {
                EMS = 1;
            }

            neuralNetwork.setInput(AA, FO, NAA, ECS, NAC, F, EMS);

            // calculate network 
            neuralNetwork.calculate();

            // get network output 
            double[] networkOutput = neuralNetwork.getOutput();
            int salida1 = (int) (networkOutput[0] + 0.5);

            if (salida1 == 0) {
                txtResultado.setText(txtNombre.getText() + " LOW RISK!!");
            } else {
                txtResultado.setText(txtNombre.getText() + " HIGH RISK!!");
            }
        }
    }//GEN-LAST:event_btnCalcularActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
        rbtAA1.isSelected();
        rbtDeficientES.isSelected();
        rbtDeficientEconS.isSelected();
        rbtDeficientF.isSelected();
        rbtNAA1.isSelected();
        rbtNAC1.isSelected();
        rbtNoFO.isSelected();
        txtNombre.setText("");
        txtResultado.setText("");
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnCreditosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreditosActionPerformed
        // TODO add your handling code here:
        frmCreditos.setVisible(true);
    }//GEN-LAST:event_btnCreditosActionPerformed

    private void rbtNAC2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtNAC2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtNAC2ActionPerformed

    private void rbtNAC3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtNAC3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtNAC3ActionPerformed

    private void btnAutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAutoActionPerformed
        // TODO add your handling code here:
        frmAutonomo.setVisible(true);
    }//GEN-LAST:event_btnAutoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
      
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmDesercionEscolar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAuto;
    private javax.swing.JButton btnCalcular;
    private javax.swing.JButton btnCreditos;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnSalir;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.ButtonGroup buttonGroup7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton rbtAA1;
    private javax.swing.JRadioButton rbtAA2;
    private javax.swing.JRadioButton rbtAA3;
    private javax.swing.JRadioButton rbtDeficientES;
    private javax.swing.JRadioButton rbtDeficientEconS;
    private javax.swing.JRadioButton rbtDeficientF;
    private javax.swing.JRadioButton rbtGoodES;
    private javax.swing.JRadioButton rbtGoodEconS;
    private javax.swing.JRadioButton rbtGoodF;
    private javax.swing.JRadioButton rbtNAA1;
    private javax.swing.JRadioButton rbtNAA2;
    private javax.swing.JRadioButton rbtNAC1;
    private javax.swing.JRadioButton rbtNAC2;
    private javax.swing.JRadioButton rbtNAC3;
    private javax.swing.JRadioButton rbtNoFO;
    private javax.swing.JRadioButton rbtRegularES;
    private javax.swing.JRadioButton rbtRegularEconS;
    private javax.swing.JRadioButton rbtRegularF;
    private javax.swing.JRadioButton rbtYesFO;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtResultado;
    // End of variables declaration//GEN-END:variables
}
